#!/usr/bin/env bash

set -euo pipefail

CMD_ARGS=(
    virt-install
    --name "${MACHINE_NAME}"
    --memory "${MACHINE_MEMORY}"
    --vcpus 1
    --os-type linux
    --boot hd
    --disk path="${ROOTFS_IMAGE}",format=qcow2
    --disk path="${CIDATA_IMAGE}"
    --network bridge="${NETWORK_DEVICE}",mac="${MACHINE_NETWORK_DHCP_MAC}"
    --network bridge="${NETWORK_DEVICE}",mac="${MACHINE_NETWORK_STATIC_MAC}"
    --graphics none
    --print-xml
)

if ssh "${LIBVIRT_HOST}" [ -e /dev/kvm ]
then
    diag echo "Enable KVM" >&2
    CMD_ARGS+=(
        --cpu host
        --os-variant virtio26
    )
fi

"${CMD_ARGS[@]}"
