#!/usr/bin/env expect

set timeout $env(MACHINE_BOOT_TIMEOUT_SECS)

spawn domain-start-or-console

expect {
  eof {
    send_user "Failed to get console (eof)"
    exit 1
  }
  timeout {
    send_user "Failed to get console (timeout)"
    exit 1
  }
  "Escape character is ^]"
}

send "\n"

expect {
  eof {
    send_user "Failed to wait for login prompt (eof)"
    exit 1
  }
  timeout {
    send_user "Failed to wait for login prompt (timeout)"
    exit 1
  }
  "$env(MACHINE_NAME) login:"
}
