#!/usr/bin/env bash

set -euo pipefail

CMD_ARGS=(
    virt-install
    --name "${DOMAIN_NAME}"
    --memory "${DOMAIN_MEMORY}"
    --vcpus 1
    --os-type linux
    --boot hd
    --disk path="${ROOTFS_IMAGE}",format=qcow2
    --disk path="${CIDATA_IMAGE}"
    --network bridge="${NETWORK_BRIDGE_NAME}",mac="${DOMAIN_DHCP_MAC_ADDRESS}"
    --network bridge="${NETWORK_BRIDGE_NAME}",mac="${DOMAIN_STATIC_MAC_ADDRESS}"
    --graphics none
    --print-xml
)

if ssh "${LIBVIRT_HOST}" [ -e /dev/kvm ]
then
    diag echo "KVM enabled" >&2
    CMD_ARGS+=(
        --cpu host
        --os-variant virtio26
    )
fi

"${CMD_ARGS[@]}"
