#!/usr/bin/env bash

set -euo pipefail

(
    if [ -f "${DISTRO_IMAGE_CACHE}" ]
    then
        diag echo "Cache used"
        cat "${DISTRO_IMAGE_CACHE}"
    else
        curl -L "${DISTRO_IMAGE_URL}"
    fi
) | push-as-root "${DISTRO_IMAGE}.part"

ssh "${LIBVIRT_HOST}" sudo mv -f "${DISTRO_IMAGE}.part" "${DISTRO_IMAGE}"
