#!/usr/bin/env bash

set -euo pipefail

if virsh list --persistent --name | grep -q "^${DOMAIN_NAME}$"
then
    echo "${DOMAIN_NAME}: Domain already defined" >&2
    exit 0
fi

DOMAIN_XML=~/domain.xml

domain-print-xml > "${DOMAIN_XML}"

virsh define "${DOMAIN_XML}"
