#!/usr/bin/env bash

set -euo pipefail

INTERVAL_SECS=${1}
MAX_RETRY=${2}

shift 2

RETRY=0

while ! "${@}"
do
    if [ ${RETRY} -le ${MAX_RETRY} ]
    then
        RETRY=$((${RETRY} + 1))
        echo "Retry after ${INTERVAL_SECS}s (${RETRY}/${MAX_RETRY})" >&2
        sleep ${INTERVAL_SECS}
    else
        echo "Failed to wait for command" >&2
        exit 1
    fi
done
