#!/usr/bin/env expect

set timeout $env(LOGIN_PROMPT_TIMEOUT_SECS)

spawn start-or-console-domain

expect {
  eof {
    send_user "Failed to get console (eof)"
    exit 1
  }
  timeout {
    send_user "Failed to get console (timeout)"
    exit 1
  }
  "Escape character is ^]"
}

send "\n"

expect {
  eof {
    send_user "Failed to wait for login prompt (eof)"
    exit 1
  }
  timeout {
    send_user "Failed to wait for login prompt (timeout)"
    exit 1
  }
  "$env(DOMAIN_NAME) login:"
}
